/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

import elements.Space;
import java.awt.Font;

/**
 *
 * @author juancamposbetancourth
 */
public class GameOver extends javax.swing.JFrame {

    /**
     * Creates new form GameOver
     */
    public GameOver() {
        initComponents();
        Font font = new Font("Comic Sans MS", Font.PLAIN, 100);
        txtGameOver.setFont(font);
        this.setSize(900, 900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReStart = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();
        txtGameOver = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReStart.setText("Reiniciar");
        btnReStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnReStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 780, 300, 60));

        btnMain.setText("Menu");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 780, 300, 60));

        txtGameOver.setForeground(new java.awt.Color(255, 255, 255));
        txtGameOver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGameOver.setText("Game over");
        txtGameOver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtGameOverMouseDragged(evt);
            }
        });
        getContentPane().add(txtGameOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 750));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/space1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -5, 910, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReStartActionPerformed
        Space space = new Space(900,900);
        Juego ventana = new Juego(space);
        ventana.setSize(900,900);
        ventana.setVisible(true);

        new Thread(() -> {
            ventana.start();
        }).start();
        this.dispose();
    }//GEN-LAST:event_btnReStartActionPerformed

    private void txtGameOverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGameOverMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGameOverMouseDragged

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:
        Menu main = new Menu();
        main.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnReStart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtGameOver;
    // End of variables declaration//GEN-END:variables
}
