/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

import elements.ReaderScore;
import java.util.Collections;
import java.util.LinkedList;

/**
 *
 * @author juancamposbetancourth
 */
public class Score extends javax.swing.JFrame {

    /**
     * Creates new form Score
     */
    public Score() {
        initComponents();
        txtScores.setText(text());
    }
    
    public String text(){
        LinkedList<Integer> scores = new LinkedList();
        ReaderScore reader = new ReaderScore();
        int valor = reader.readLinee();
        String resultado = "";
        int cont = 1;
        while (valor != -1) {
            scores.add(valor);
            valor = reader.readLinee();
        }
        Collections.sort(scores, Collections.reverseOrder());
        for(Integer actual: scores){
            resultado = resultado +cont+".         "+ actual + "\n" ;
            cont++; 
        }
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtScores = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnMenu = new javax.swing.JButton();
        txtSky = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtScores.setColumns(20);
        txtScores.setRows(5);
        getContentPane().add(txtScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 530, 210));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, -1));

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 250, 80));

        txtSky.setForeground(new java.awt.Color(255, 255, 255));
        txtSky.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSky.setText("Sky Hunters");
        txtSky.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtSkyMouseDragged(evt);
            }
        });
        getContentPane().add(txtSky, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 750));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/space1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -5, 910, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setSize(900,900);
        menu.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtSkyMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSkyMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkyMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtScores;
    private javax.swing.JLabel txtSky;
    // End of variables declaration//GEN-END:variables
}
